#pragma once

#include <cmath>
#include <algorithm>
#include <thread>
#include <mutex>
#include <iomanip>
#include <iostream>
#include <sstream>
#include <string>
#include <array>
#include <vector>
#include <list>
#include <optional>
#include <random>
#include <numbers>
#include <format>
#include <unordered_set>
#include <unordered_map>
#include <functional>
#include <memory>
#include <filesystem>
#include <span>
#include <fstream>
